name = "LeanFM"
version = "0.1.0"
defaultTargets = ["leanfm"]

[[lean_lib]]
name = "LeanFM"

[[lean_exe]]
name = "leanfm"
root = "Main"

[[lean_exe]]
name = "leanfm-server"
root = "Server"

[[lean_exe]]
name = "leanfm-diagrams"
root = "Diagrams"
