-- Generated by scripts/embed_assets.js. Edit assets/*.js; this file stays readable.
import LeanFM.Assets

namespace LeanFM.GeneratedAssets

def subjectGraphJs : String := include_str "../assets/subjectGraph.js"

def assistantJs : String := include_str "../assets/assistant.js"

def aggregateGraphJs : String := include_str "../assets/aggregateGraph.js"

def subjectGraphJsAsset : LeanFM.GeneratedAsset :=
  { name := "subjectGraph.js"
  , kind := .javascript
  , mediaType := "application/javascript"
  , body := subjectGraphJs
  , requires := ["subjectGraph", "LeanFMUI", "renderMarkdown"]
  }

def assistantJsAsset : LeanFM.GeneratedAsset :=
  { name := "assistant.js"
  , kind := .javascript
  , mediaType := "application/javascript"
  , body := assistantJs
  , requires := ["chatPrompt", "chartDatasets", "validateSpec"]
  }

def aggregateGraphJsAsset : LeanFM.GeneratedAsset :=
  { name := "aggregateGraph.js"
  , kind := .javascript
  , mediaType := "application/javascript"
  , body := aggregateGraphJs
  , requires := ["aggGraph", "groupMarkdown", "drawAgg"]
  }

def allAssets : List LeanFM.GeneratedAsset :=
  [subjectGraphJsAsset, assistantJsAsset, aggregateGraphJsAsset]

def validation : LeanFM.AssetValidation :=
  LeanFM.validateAssets allAssets

def validationReport : String :=
  LeanFM.assetValidationReport validation

end LeanFM.GeneratedAssets
