-- Generated by scripts/embed_static_assets.js. Edit assets/*.js; this file stays readable.
import LeanFM.Assets

namespace LeanFM.StaticAssets

-- subjectGraph.js sha256:1ce8cb85e13f9fe8
def subjectGraphJs : String := include_str "../assets/subjectGraph.js"

-- assistant.js sha256:b636ddd2751933f4
def assistantJs : String := include_str "../assets/assistant.js"

-- aggregateGraph.js sha256:17b0ad6737e458a7
def aggregateGraphJs : String := include_str "../assets/aggregateGraph.js"

def subjectGraphJsAsset : LeanFM.StaticAsset :=
  { name := "subjectGraph.js"
  , kind := .javascript
  , mediaType := "application/javascript"
  , body := subjectGraphJs
  , requires := ["subjectGraph", "LeanFMUI", "renderMarkdown"]
  }

def assistantJsAsset : LeanFM.StaticAsset :=
  { name := "assistant.js"
  , kind := .javascript
  , mediaType := "application/javascript"
  , body := assistantJs
  , requires := ["chatPrompt", "chartDatasets", "validateSpec"]
  }

def aggregateGraphJsAsset : LeanFM.StaticAsset :=
  { name := "aggregateGraph.js"
  , kind := .javascript
  , mediaType := "application/javascript"
  , body := aggregateGraphJs
  , requires := ["aggGraph", "groupMarkdown", "drawAgg"]
  }

def allAssets : List LeanFM.StaticAsset :=
  [subjectGraphJsAsset, assistantJsAsset, aggregateGraphJsAsset]

def validation : LeanFM.AssetValidation :=
  LeanFM.validateStaticAssets allAssets

def validationReport : String :=
  LeanFM.staticAssetValidationReport validation

end LeanFM.StaticAssets
