const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const assets = [
  {
    defName: "subjectGraphJs",
    assetName: "subjectGraph.js",
    rel: "assets/subjectGraph.js",
    requires: ["subjectGraph", "LeanFMUI", "renderMarkdown"]
  },
  {
    defName: "assistantJs",
    assetName: "assistant.js",
    rel: "assets/assistant.js",
    requires: ["chatPrompt", "chartDatasets", "validateSpec"]
  },
  {
    defName: "aggregateGraphJs",
    assetName: "aggregateGraph.js",
    rel: "assets/aggregateGraph.js",
    requires: ["aggGraph", "groupMarkdown", "drawAgg"]
  },
];

function leanString(text) {
  return JSON.stringify(text)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

const lines = [
  "-- Generated by scripts/embed_assets.js. Edit assets/*.js, then regenerate.",
  "import LeanFM.Assets",
  "",
  "namespace LeanFM.GeneratedAssets",
  "",
];

for (const asset of assets) {
  const { defName, rel } = asset;
  const text = fs.readFileSync(path.join(root, rel), "utf8");
  lines.push(`def ${defName} : String := ${leanString(text)}`);
  lines.push("");
}

function leanList(xs) {
  return "[" + xs.map(leanString).join(", ") + "]";
}

for (const asset of assets) {
  lines.push(`def ${asset.defName}Asset : LeanFM.GeneratedAsset :=`);
  lines.push(`  { name := ${leanString(asset.assetName)}`);
  lines.push("  , kind := .javascript");
  lines.push("  , mediaType := \"application/javascript\"");
  lines.push(`  , body := ${asset.defName}`);
  lines.push(`  , requires := ${leanList(asset.requires)}`);
  lines.push("  }");
  lines.push("");
}

lines.push("def allAssets : List LeanFM.GeneratedAsset :=");
lines.push("  [" + assets.map(asset => `${asset.defName}Asset`).join(", ") + "]");
lines.push("");
lines.push("def validation : LeanFM.AssetValidation :=");
lines.push("  LeanFM.validateAssets allAssets");
lines.push("");
lines.push("def validationReport : String :=");
lines.push("  LeanFM.assetValidationReport validation");
lines.push("");

lines.push("end LeanFM.GeneratedAssets");
lines.push("");

fs.mkdirSync(path.join(root, "LeanFM"), { recursive: true });
fs.writeFileSync(path.join(root, "LeanFM", "GeneratedAssets.lean"), lines.join("\n"));
