const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const root = path.resolve(__dirname, "..");
const assets = [
  {
    defName: "subjectGraphJs",
    assetName: "subjectGraph.js",
    rel: "assets/subjectGraph.js",
    requires: ["subjectGraph", "LeanFMUI", "renderMarkdown"]
  },
  {
    defName: "assistantJs",
    assetName: "assistant.js",
    rel: "assets/assistant.js",
    requires: ["chatPrompt", "chartDatasets", "validateSpec"]
  },
  {
    defName: "aggregateGraphJs",
    assetName: "aggregateGraph.js",
    rel: "assets/aggregateGraph.js",
    requires: ["aggGraph", "groupMarkdown", "drawAgg"]
  },
];

const lines = [
  "-- Generated by scripts/embed_assets.js. Edit assets/*.js; this file stays readable.",
  "import LeanFM.Assets",
  "",
  "namespace LeanFM.GeneratedAssets",
  "",
];

for (const asset of assets) {
  const relFromLean = path.relative(path.join(root, "LeanFM"), path.join(root, asset.rel));
  const text = fs.readFileSync(path.join(root, asset.rel), "utf8");
  const hash = crypto.createHash("sha256").update(text).digest("hex").slice(0, 16);
  lines.push(`-- ${asset.assetName} sha256:${hash}`);
  lines.push(`def ${asset.defName} : String := include_str ${JSON.stringify(relFromLean)}`);
  lines.push("");
}

function leanList(xs) {
  return "[" + xs.map(JSON.stringify).join(", ") + "]";
}

for (const asset of assets) {
  lines.push(`def ${asset.defName}Asset : LeanFM.GeneratedAsset :=`);
  lines.push(`  { name := ${JSON.stringify(asset.assetName)}`);
  lines.push("  , kind := .javascript");
  lines.push("  , mediaType := \"application/javascript\"");
  lines.push(`  , body := ${asset.defName}`);
  lines.push(`  , requires := ${leanList(asset.requires)}`);
  lines.push("  }");
  lines.push("");
}

lines.push("def allAssets : List LeanFM.GeneratedAsset :=");
lines.push("  [" + assets.map(asset => `${asset.defName}Asset`).join(", ") + "]");
lines.push("");
lines.push("def validation : LeanFM.AssetValidation :=");
lines.push("  LeanFM.validateAssets allAssets");
lines.push("");
lines.push("def validationReport : String :=");
lines.push("  LeanFM.assetValidationReport validation");
lines.push("");

lines.push("end LeanFM.GeneratedAssets");
lines.push("");

fs.mkdirSync(path.join(root, "LeanFM"), { recursive: true });
fs.writeFileSync(path.join(root, "LeanFM", "GeneratedAssets.lean"), lines.join("\n"));
