const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const assets = [
  ["subjectGraphJs", "assets/subjectGraph.js"],
  ["assistantJs", "assets/assistant.js"],
  ["aggregateGraphJs", "assets/aggregateGraph.js"],
];

function leanString(text) {
  return JSON.stringify(text)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

const lines = [
  "-- Generated by scripts/embed_assets.js. Edit assets/*.js, then regenerate.",
  "namespace LeanFM.GeneratedAssets",
  "",
];

for (const [name, rel] of assets) {
  const text = fs.readFileSync(path.join(root, rel), "utf8");
  lines.push(`def ${name} : String := ${leanString(text)}`);
  lines.push("");
}

lines.push("end LeanFM.GeneratedAssets");
lines.push("");

fs.mkdirSync(path.join(root, "LeanFM"), { recursive: true });
fs.writeFileSync(path.join(root, "LeanFM", "GeneratedAssets.lean"), lines.join("\n"));
